// Generated by CoffeeScript 1.8.0
(function() {
  var finish_loading, getWinSize, next_page, on_loading;

  getWinSize = function() {
    var padLandscape, padPortrait, pc, phoneLandscape, winWidth;
    phoneLandscape = 568;
    padPortrait = 768;
    padLandscape = 1024;
    pc = 1200;
    winWidth = $(window).width();
    if (winWidth < phoneLandscape) {
      return 1;
    } else if (winWidth >= phoneLandscape && winWidth < padPortrait) {
      return 2;
    } else if (winWidth >= padPortrait && winWidth < padLandscape) {
      return 3;
    } else if (winWidth >= padLandscape && winWidth < pc) {
      return 4;
    } else {
      return 5;
    }
  };

  on_loading = false;

  finish_loading = false;

  next_page = 2;

  this.auto_list_layout = function() {
    var img, img_dom, post, post_dom, _i, _j, _len, _len1, _ref, _ref1, _results;
    _ref = $(".list .post");
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      post = _ref[_i];
      post_dom = $(post);
      if (post_dom.find('a').length && getWinSize() < 3) {
        post_dom.unbind('click');
        post_dom.click(function() {
          return location.href = $($('.list .post')[$(this).index()]).find('a').attr('href');
        });
      }
      if (post_dom.find('img').length) {
        post_dom.addClass('img');
        if (getWinSize() < 3) {
          post_dom.css("background-image", "url(" + post_dom.find("img").attr("src") + ")");
        } else {
          post_dom.removeAttr('style');
        }
      } else {
        post_dom.addClass('text');
      }
    }
    if (getWinSize() < 3) {
      _ref1 = $(".list .img");
      _results = [];
      for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
        img = _ref1[_j];
        img_dom = $(img);
        _results.push(img_dom.css("background-image", "url(" + img_dom.find("img").attr("src") + ")"));
      }
      return _results;
    } else {
      return $(".list .img").removeAttr("style");
    }
  };

  this.auto_loading = function() {
    var bottom_diff, url;
    bottom_diff = $(document).height() - $(window).height() - $(window).scrollTop();
    if (getWinSize() < 3 && bottom_diff < 150 && $('.list').length && !on_loading && !finish_loading && location.search.indexOf('?s=') === -1) {
      on_loading = true;
      $('#on_loading').removeClass('hidden');
      url = location.pathname + 'page/' + next_page;
      url = url.replace(/\/{2,}/g, '/');
      return $.get(url, {
        'pjax': 'true'
      }, function(data) {
        if (data.length < 20) {
          finish_loading = true;
        } else {
          $('.list').append(data);
          auto_list_layout();
          next_page += 1;
          on_loading = false;
        }
        return $('#on_loading').addClass('hidden');
      });
    }
  };

  $(document).ready(function() {
    if ($(".list").length) {
      auto_list_layout();
    }
    $(window).resize(auto_list_layout);
    $(window).scroll(auto_loading);
    return auto_loading();
  });

}).call(this);
